### ISSUE TITLE
"variation of interest" seems to be split across axis 2 instead of axis 1, as expected?

### ISSUE THREAD

**Issue by fedarko** [cjm007/DEICODE#52] opened 2019-12-02 20:19 UTC
Other people in the lab and I have observed this with multiple pretty distinct datasets on DEICODE.

We discussed this this morning -- this might be an artifact of the eigenvalues? produced by scipy's SVD method being flipped, somehow (either before, during, or after `deicode/rpca.py` [calls that function](https://github.com/biocore/DEICODE/blob/b1f37059b79f6ca2e2db11ba2fb7500c1a92f87e/deicode/rpca.py#L45)).

One of the datasets this happens with, weirdly enough, is the sleep apnea dataset used in the DEICODE paper. We'd expect the sample metadata value `exposure_type` (two values: `Air` or `IHH`) to explain most of the sample variation in the biplot, but the corresponding "separation" seems to be split mostly along Axis 2 now (not Axis 1, as was shown in the paper). **See biplot below:**

![biplot](https://user-images.githubusercontent.com/4177727/69990620-e257b600-14fa-11ea-8c5e-1446e1b53a21.png)

For reference, this was generated using DEICODE 0.2.3 in a QIIME 2019.10 environment (using scipy 1.3.1). Can send over the QZV file (which contains provenance / version info), if you'd like.

As another way of looking at this: **in Qurro**, taking the log-ratio of the top 30 to bottom 30 features for PC 1 doesn't show much separation between Air and IHH exposure_types; however, for PC 2, the same log-ratio (but with different features, based instead on the PC 2 feature loadings) shows clear separation that seems to be analogous to what is shown in the DEICODE paper.

see below qurro plots for reference (sidenote, next version of Qurro will have controls to make doing these selections a lot easier... did this in Qurro 0.4.0 for reference.)

**Axis 1:**

![axis1](https://user-images.githubusercontent.com/4177727/69989916-8d677000-14f9-11ea-84b8-3d7b6f2efadb.png)

**Axis 2:**

![axis2](https://user-images.githubusercontent.com/4177727/69989922-8f313380-14f9-11ea-9272-9cbd970524b5.png)

Lastly, looking in Qurro at the log-ratio of Coriobacteriaceae to Clostridium (shown in Figure 5 in the DEICODE paper) shows that features classified as belonging to these groups are extremely ranked (roughly similar to what's shown in Fig. 5, but flipped?) mostly for Axis 2, but not for Axis 1:

**Axis 1:**
![cc1](https://user-images.githubusercontent.com/4177727/69991545-be956f80-14fc-11ea-980b-1c036d2e0875.png)

**Axis 2:**
![cc2](https://user-images.githubusercontent.com/4177727/69991544-be956f80-14fc-11ea-9c4b-440e4562eb72.png)

**Axis 3:**
![cc3](https://user-images.githubusercontent.com/4177727/69991543-bdfcd900-14fc-11ea-9981-94f1f64f7f45.png)

To me, it seems like somewhere along the line things started getting "flipped" or otherwise switched around somehow. The fact that the sleep apnea dataset only started experiencing this at a certain point should make it possible to test this -- the "brute force" testing method would just be going back to an old version of DEICODE and seeing if this problem is still present, and if not increasing the version until you find where the switch happened (could use something like binary search I guess :) We could theoretically automate this process, but taking the time to do that might be slower than just manual testing.

If that testing doesn't work (i.e. all versions of DEICODE show this problem???), we could try messing with the scipy version / other SVD parameters as we discussed this morning and seeing if that impacts things? Or this might be another bug from somewhere else.

...Also, this all presupposes that the paper figures' separation among PC 1 is what is the "correct" output. It could also be the case that those are wrong and the latest behavior is correct instead (but the whole consistently-separating-among-axis-2 thing is fishy, and makes me think that the current behavior is a reflection of a problem that was introduced somewhere).

**Comment by mortonjt** [comment] 2019-12-02 20:25
Is this related to this issue?  https://github.com/biocore/DEICODE/issues/32

**Comment by fedarko** [comment] 2019-12-02 21:28
It might be. As I understand it the problem in #32 was that the eigenvalues were in increasing instead of decreasing order (?), and in the sleep apnea biplot produced by DEICODE things seem to be properly decreasing (although speaking off-hand these seem like pretty huge eigenvalues, I guess? at least compared to what I'm used to seeing in these sorts of files.)

![deicodething](https://user-images.githubusercontent.com/4177727/69995612-441d1d80-1505-11ea-9d3b-53c05835ee32.png)

Perhaps the change to #32 may have caused this problem, or failed to account for it -- @mortonjt's comment [here](https://github.com/biocore/DEICODE/pull/33#discussion_r275590323) stands out to me as something that might be worth trying.

**Comment by cameronmartino** [comment] 2019-12-02 22:51
I am a bit confused because of the following re-centering that relies on [scipy's svd function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html) 

https://github.com/biocore/DEICODE/blob/b1f37059b79f6ca2e2db11ba2fb7500c1a92f87e/deicode/rpca.py#L9

which outputs already sorted in "non-increasing order". Therefore the argsort function should not change anything. @mortonjt do you think this could be caused by gesdd not converging?

https://github.com/biocore/DEICODE/blob/b1f37059b79f6ca2e2db11ba2fb7500c1a92f87e/deicode/rpca.py#L45-L58

**Comment by cameronmartino** [comment] 2020-01-11 00:23
closing this as it should be addressed in PR #54. Reopen if you experience more issues.

**Closed as completed by cameronmartino** 2020-01-11 00:23 UTC
